"""Add tracking code and customer note to Order

Revision ID: 0a16f52a2410
Revises: 11f029caba3f
Create Date: 2026-04-29 08:26:42.583792

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0a16f52a2410'
down_revision: Union[str, None] = '11f029caba3f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('tracking_code', sa.String(), nullable=True))
    op.add_column('orders', sa.Column('customer_note', sa.Text(), nullable=True))
    op.create_index(op.f('ix_orders_tracking_code'), 'orders', ['tracking_code'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_orders_tracking_code'), table_name='orders')
    op.drop_column('orders', 'customer_note')
    op.drop_column('orders', 'tracking_code')
    # ### end Alembic commands ###
