"""Add Supplier role and fields

Revision ID: 8cb706828050
Revises: 0a16f52a2410
Create Date: 2026-04-29 22:13:46.908807

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8cb706828050'
down_revision: Union[str, None] = '0a16f52a2410'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('supplier_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'orders', 'users', ['supplier_id'], ['id'])
    op.add_column('users', sa.Column('supplier_code', sa.String(), nullable=True))
    op.add_column('users', sa.Column('company_name', sa.String(), nullable=True))
    op.create_index(op.f('ix_users_supplier_code'), 'users', ['supplier_code'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_supplier_code'), table_name='users')
    op.drop_column('users', 'company_name')
    op.drop_column('users', 'supplier_code')
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.drop_column('orders', 'supplier_id')
    # ### end Alembic commands ###
