"""add courier code

Revision ID: a34b5a0396a2
Revises: 8cb706828050
Create Date: 2026-06-08 08:01:45.140176

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a34b5a0396a2'
down_revision: Union[str, None] = '8cb706828050'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('couriers', sa.Column('courier_code', sa.String(), nullable=True))
    op.create_index(op.f('ix_couriers_courier_code'), 'couriers', ['courier_code'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_couriers_courier_code'), table_name='couriers')
    op.drop_column('couriers', 'courier_code')
    # ### end Alembic commands ###
